### ISSUE TITLE
Various smaller issues with the wysiwyg editor

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#519]
Leftovers from https://github.com/cobudget/cobudget/pull/360

* [ ] Doesn't ssr https://github.com/remirror/remirror/issues/1349
* [ ] Doesn't support tables https://github.com/remirror/remirror/issues/1356
* [ ] Doesn't support task lists (checklists) https://github.com/remirror/remirror/issues/1357
* [ ] A bit bad performance when typing. Seems a bit better in prod https://github.com/remirror/remirror/issues/1366
* [ ] Re-add image upload. We have code working for this with cloudinary but we commented that out for now since we want to switch to another image processing service

**Comment by Powersource** [comment]
I think the easiest solution to these is probably to pay the developers a little bit. But i also found this library which could be a good option https://github.com/Saul-Mirone/milkdown

**Comment by schroeder-g** [comment]
Hi @Powersource , 

Reaching out because my team and I are in the midst of implementing a WYSIWYG markdown editor in a `next` context as well, and having a rather difficult time settling on a library that plays nicely with the framework. We had started working with milkdown as it happens, but ran into other issues -- in particular an error with the use of require syntax (see [this stackoverflow post](https://stackoverflow.com/questions/65974337/import-es-module-in-next-js-err-require-esm) for the error particulars). 

Just curious from your perspective is it feasible to work around the global css imports error you mentioned above?

Also just FYI while you're shopping around I would _not_ recommend looking at `rich-markdown-editor`, it has been archived by its sole maintainer.

**Comment by schroeder-g** [comment]
Hi @Powersource an update on milkdown; seems like it was a result of an outdated version of `next`. Please disregard my disparaging comments above!

**Comment by Powersource** [comment]
@schroeder-g iirc i was able to work around the css issue. but some other issues remained for ssr, and it sounded unclear if the library would support ssr any time soon/ever. however we just don't render that component serverside. we're currently using it in production and i think it's working well.

**Comment by Powersource** [comment]
Tables and task lists should be supported now if we update!
